/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as OfflineImport } from './routes/offline'
import { Route as IndexImport } from './routes/index'
import { Route as RoomIndexImport } from './routes/room/index'
import { Route as RoomRoomIdImport } from './routes/room/$roomId'

// Create/Update Routes

const OfflineRoute = OfflineImport.update({
  id: '/offline',
  path: '/offline',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const RoomIndexRoute = RoomIndexImport.update({
  id: '/room/',
  path: '/room/',
  getParentRoute: () => rootRoute,
} as any)

const RoomRoomIdRoute = RoomRoomIdImport.update({
  id: '/room/$roomId',
  path: '/room/$roomId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/offline': {
      id: '/offline'
      path: '/offline'
      fullPath: '/offline'
      preLoaderRoute: typeof OfflineImport
      parentRoute: typeof rootRoute
    }
    '/room/$roomId': {
      id: '/room/$roomId'
      path: '/room/$roomId'
      fullPath: '/room/$roomId'
      preLoaderRoute: typeof RoomRoomIdImport
      parentRoute: typeof rootRoute
    }
    '/room/': {
      id: '/room/'
      path: '/room'
      fullPath: '/room'
      preLoaderRoute: typeof RoomIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/offline': typeof OfflineRoute
  '/room/$roomId': typeof RoomRoomIdRoute
  '/room': typeof RoomIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/offline': typeof OfflineRoute
  '/room/$roomId': typeof RoomRoomIdRoute
  '/room': typeof RoomIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/offline': typeof OfflineRoute
  '/room/$roomId': typeof RoomRoomIdRoute
  '/room/': typeof RoomIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/offline' | '/room/$roomId' | '/room'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/offline' | '/room/$roomId' | '/room'
  id: '__root__' | '/' | '/offline' | '/room/$roomId' | '/room/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OfflineRoute: typeof OfflineRoute
  RoomRoomIdRoute: typeof RoomRoomIdRoute
  RoomIndexRoute: typeof RoomIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OfflineRoute: OfflineRoute,
  RoomRoomIdRoute: RoomRoomIdRoute,
  RoomIndexRoute: RoomIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/offline",
        "/room/$roomId",
        "/room/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/offline": {
      "filePath": "offline.tsx"
    },
    "/room/$roomId": {
      "filePath": "room/$roomId.tsx"
    },
    "/room/": {
      "filePath": "room/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
